# Generated by Django 2.0.2 on 2018-03-07 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(help_text='Қаланың атын еңгізіңіз', max_length=50)),
                ('region', models.CharField(help_text='Қаланың районың еңгізіңіз', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(help_text='Есімің еңгізіңіз', max_length=50)),
                ('LastName', models.CharField(help_text='Тегін еңгізіңіз', max_length=50)),
                ('Email', models.CharField(help_text='Почтасын еңгізіңіз', max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('Items', models.CharField(help_text='Пәндерің еңгізіңіз', max_length=50)),
                ('Receipts', models.CharField(help_text='Максатын еңгізіңіз', max_length=50)),
                ('Phone', models.CharField(help_text='20 саннан тұрады. Телефон нөмерін еңгізіңіз', max_length=20, verbose_name='Phone')),
                ('Address', models.CharField(help_text='Адресын еңгізіңіз', max_length=50, verbose_name='Address')),
                ('location', models.ManyToManyField(help_text='Select a location for this student', to='catalog.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Аты-жөнің еңгізіңіз', max_length=100)),
                ('Email', models.CharField(help_text='Почтасын еңгізіңіз', max_length=50)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('Items', models.CharField(help_text='Пәндерің еңгізіңіз', max_length=50)),
                ('Phone', models.CharField(help_text='20 саннан тұрады. Телефон нөмерін еңгізіңіз', max_length=20, verbose_name='Phone')),
                ('Address', models.CharField(help_text='Адресын еңгізіңіз', max_length=50, verbose_name='Address')),
                ('location', models.ManyToManyField(help_text='Select a location for this teacher', to='catalog.Location')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Teacher'),
        ),
    ]
